# Module 3: Data Structures Assignments
## Lesson 3.1: Lists

### Assignment 1: Creating and Accessing Lists

Create a list of the first 20 positive integers. Print the list.

In [1]:
l = []
for i in range(1,21):
    l.append(i)
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


### Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.

In [3]:
l = []
for i in range(1,21):
    l.append(i)
print(l)

print(l[0])  # First element
print(l[-1]) # Last element
print(len(l)//2) # Middle element

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
1
20
10


### Assignment 3: List Slicing

Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.

In [4]:
l = []
for i in range(1,21):
    l.append(i)
print(l)

print(l[:5])    # First five elements
print(l[-5:])   # Last five elements
print(l[5:16])  # Elements from index 5 to 15

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5]
[16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


### Assignment 4: List Comprehensions

Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.

In [5]:
x = [ i*i for i in range(1,10)]
print(x)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


### Assignment 5: Filtering Lists

Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.

In [6]:
l = []
for i in range(1,21):
    l.append(i)
print(l)

x = [ i for i in l if i%2==0]; print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


### Assignment 6: List Methods

Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

In [7]:
import random
l = []
for i in range(1,21):
    l.append(random.randint(1,100))
print(l)
l.sort()
print(l)    
l.sort(reverse=True)
print(l)        
print(list(set(l)))

[29, 91, 81, 63, 76, 74, 36, 13, 19, 42, 14, 42, 78, 51, 75, 63, 38, 50, 16, 95]
[13, 14, 16, 19, 29, 36, 38, 42, 42, 50, 51, 63, 63, 74, 75, 76, 78, 81, 91, 95]
[95, 91, 81, 78, 76, 75, 74, 63, 63, 51, 50, 42, 42, 38, 36, 29, 19, 16, 14, 13]
[36, 38, 74, 75, 76, 42, 78, 14, 16, 81, 50, 51, 29, 19, 13, 91, 63, 95]


### Assignment 7: Nested Lists

Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

In [9]:
import random
l = []
for i in range(3):
    l.append([random.randint(1,100) for _ in range(3)])

print(l)
for i in l:
    print(i)

[[37, 75, 50], [23, 21, 18], [48, 98, 69]]
[37, 75, 50]
[23, 21, 18]
[48, 98, 69]


### Assignment 8: List of Dictionaries

Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

In [28]:
list_dict = []

num = int(input("Enter the number of students: "))
for i in range(num):
    name = input("Enter the name of student: ")
    score = input("Enter the score of student: ")
    d = dict()
    d["Name"] = name
    d["Score"]= score
    list_dict.append(d)
print(list_dict)

from operator import itemgetter
sorted_std = sorted(list_dict, key=itemgetter('Score'), reverse=True)
print("Students sorted by score in descending order:")
for student in sorted_std:
    print(student)

[{'Name': 'Swaraj', 'Score': '89'}, {'Name': 'Prajakta', 'Score': '99'}]
Students sorted by score in descending order:
{'Name': 'Prajakta', 'Score': '99'}
{'Name': 'Swaraj', 'Score': '89'}


### Assignment 9: Matrix Transposition

Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.2


In [29]:
l1 = []
for i in range(1,4):
    l2 = []
    for j in range(1,4):
        num = int(input(f"Enter element for position ({i},{j}): "))
        l2.append(num)
    l1.append(l2)
print("The matrix:")
print(l1)

import numpy as np
matrix = np.array(l1)
transposed = matrix.T
print("Transposed matrix:")
print(transposed)

The matrix:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Assignment 10: Flattening a Nested List

Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

In [31]:
def Flatten(list1):
    flat_list = []
    for sublist in list1:
        for item in sublist:
            flat_list.append(item)
    return flat_list
nested_list = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
flat_list = Flatten(nested_list)
print("Original nested list:", nested_list)
print("Flattened list:", flat_list)

Original nested list: [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


### Assignment 11: List Manipulation

Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.

In [32]:
l1 = []
for i in range(1,11):
    l1.append(i)
print(l1)

print(l1[2:7:2])
l1.insert(5,99)
print(l1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 5, 7]
[1, 2, 3, 4, 5, 99, 6, 7, 8, 9, 10]


### Assignment 12: List Zipping

Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

In [33]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = zip(l1,l2)
print(list(l3))

[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)]


### Assignment 13: List Reversal

Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

In [34]:
def ReverseList(input_list):
    return input_list[::-1]

original_list = [1, 2, 3, 4, 5]
reversed_list = ReverseList(original_list)
print("Original list:", original_list)
print("Reversed list:", reversed_list)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


### Assignment 14: List Rotation

Write a function that rotates a list by n positions. Print the original and rotated lists.

In [35]:
def RotateList(input_list, n):
    return input_list[n:] + input_list[:n]  

original_list = [1, 2, 3, 4, 5]
n = 2  # Number of positions to rotate
rotated_list = RotateList(original_list, n)
print("Original list:", original_list)
print(f"List after rotating by {n} positions:", rotated_list)

Original list: [1, 2, 3, 4, 5]
List after rotating by 2 positions: [3, 4, 5, 1, 2]


### Assignment 15: List Intersection

Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

In [37]:
l1 = [1,2,3,4,5,6,7,8,9,10 ]
l2 = [2,4,6,8,10,11,12,13,14,15,15,16,17,18,19,20]
common_elements = list(set(l1) & set(l2))
print("Common elements between l1 and l2:", common_elements)

Common elements between l1 and l2: [2, 4, 6, 8, 10]
